#! /usr/bin/env python
# coding=utf-8

'''JIRA CLI'''

import sys
reload(sys)
sys.setdefaultencoding('utf-8')
import os.path
from argparse import ArgumentParser, ArgumentDefaultsHelpFormatter
import subprocess
import urllib
import json
import ConfigParser
import re
import textwrap
import itertools
import cli, readline
import tab
import time
import pprint
import threading

URL = '/rest/api/latest'
MAXRESULTS = 50
WIDTH = 20

COMP, DESC, OLDCOMM, COMM = range(4)
NONE, VERSION, COMPONENT = range(3) # Grouping

# Fields
REHEAD = re.compile(r'^>>> [^/]+/(?P<key>(?P<proj>[A-Z]+)-\S+) (?P<summ>.*)$')
REFOOT = re.compile(r'^<<< [^/]+/[A-Z]+-\S+ .*$')
RETYPE = re.compile(r'^Type: +(?P<type>.+) +Status: +(?P<stat>.*?)(?: # .*)?$')
REPRIO = re.compile(r'^Priority: +(?P<prio>.+) +Resolution: +(?P<res>.*)$')
RECOMP = re.compile(r'^(Component: +(?P<comp>.+?))?( +Version: +(?P<ver>.+))?$')
RECREA = re.compile(r'^Created: +(?P<crea>.+) +Security: +(?P<sec>.*)$')
REUPDA = re.compile(r'^Updated: +(?P<upda>.+) +Assignee: +(?P<asn>.*)$')
RERESO = re.compile(r'^Resolved: +(?P<reso>.+) +Reporter: +(?P<rep>.*)$')
RECOMM = re.compile(r'^Comment from \w+, \S+:$')

# Index
REISSU = re.compile(r'^(?P<open>o)?(?:(?:└|├)─>)?(?P<key>[A-Z]+-\d+) +.*$')
REGROU = re.compile(r'^"\s+(?P<grouping>.*)$')
REBLAN = re.compile(r'^\s*$')

# Messages
UNAVAILMSG = "JIRA is unavailable"

def row(issues, key, fields, child=''):
    '''Return row of issue field values'''

    values = [child + key]
    for field in fields:
        if isinstance(issues[key][field], list):
            values.append(', '.join(issues[key][field]))
        else:
            values.append(issues[key][field])

    return values

def subset(needle, haystack):
    '''Return whether needle is a subset of haystack'''

    if isinstance(needle, list) and isinstance(haystack, list):
        for item0, item1 in itertools.izip_longest(needle, haystack):
            if not subset(item0, item1):
                return False
    elif isinstance(needle, dict) and isinstance(haystack, dict):
        for item in needle:
            if not subset(needle[item], haystack[item]):
                return False
    elif isinstance(needle, str) and isinstance(haystack, unicode):
        return needle.replace('\r', '') == haystack.replace('\r', '')
    else:
        return needle == haystack

    return True

def parseissue(temp):
    '''Parse issue form'''

    # A list of (key, {}) rather than a dictionary keyed on the issue
    # key so we can issues with the same key, as when we create many in
    # one go (e.g. literally 'AA-???').
    issues = [] 

    state = None
    for line in temp:
        # Ignore comments at the start of the view
        if not state and line[0] == '#':
            continue

        # Parse line
        match = REHEAD.match(line[:-1])
        if match:
            issue = {'fields': {}, 'comment': '', 'comments': [],
                     'transition': {}}
            fields = issue['fields']

            key = match.group('key')
            fields['project'] = {'key': match.group('proj')}
            summary = match.group('summ')

            issues.append((key, issue))
            fields['summary'] = summary
            continue

        match = RETYPE.match(line[:-1])
        if match:
            fields['issuetype'] = {'name': match.group('type').strip()}
            issue['transition'] = match.group('stat')
            continue

        match = REPRIO.match(line[:-1])
        if match:
            fields['priority'] = {'name': match.group('prio').strip()}
            continue

        match = RECOMP.match(line[:-1])
        if match and line[:-1]: # But don't eat empty lines
            component = match.group('comp')
            if component:
                if 'components' in fields:
                    components = fields['components']
                    components.append({'name': component.strip()})
                else:
                    fields['components'] = [{'name': component.strip()}]

            version = match.group('ver')
            if version:
                if 'fixVersions' in fields:
                    versions = fields['fixVersions']
                    versions.append({'name': version.strip()})
                else:
                    fields['fixVersions'] = \
                        [{'name': version.strip()}]
            continue

        match = RECREA.match(line[:-1])
        if match:
            # Let's not touch dates for now
            sec = match.group('sec').strip()
            if sec:
                fields['security'] = {'name': sec}
            continue

        match = REUPDA.match(line[:-1])
        if match:
            # Let's not touch dates for now
            asn = match.group('asn').strip()
            fields['assignee'] = {'name': asn} if asn else None
            continue

        match = RERESO.match(line[:-1])
        if match:
            # Let's not touch dates for now
            rep = match.group('rep').strip()
            fields['reporter'] = {'name': rep} if rep else None
            continue

        if line[:-1] == 'Description:':
            fields['description'] = ''
            state = DESC
            continue

        if RECOMM.match(line[:-1]):
            state = OLDCOMM

            # Strip last old comment since we know we won't have another one
            if issue['comments']:
                issue['comments'][-1]['body'] = \
                    issue['comments'][-1]['body'][:-2]

            issue['comments'].append({'body': ''})
            continue

        if line[:-1] == 'New Comment?':
            # Strip last old comment since we know we won't have another one
            if issue['comments']:
                issue['comments'][-1]['body'] = \
                    issue['comments'][-1]['body'][:-2]

            state = COMM
            continue

        if REFOOT.match(line[:-1]):
            # Description is done - remove new line
            if 'description' in fields:
                fields['description'] = fields['description'].rstrip()

            issue['comment'] = issue['comment'].strip()
            state = None
            continue

        # Handle state
        if state == DESC:
            fields['description'] += line
        elif state == COMM:
            issue['comment'] += line
        elif state == OLDCOMM:
            issue['comments'][-1]['body'] += line

    return issues

def parseissues(temp, grouping=None):
    '''Parse issue index'''

    issues = {}
    groups = []
    toopen = []
    for line in temp:
        # Is it a comment?
        if line[0] == '#':
            continue

        # Is it an issue?
        match = REISSU.match(line)
        if match:
            if grouping:
                issues[match.group('key')] = {grouping: groups}
            if match.group('open'):
                toopen.append(match.group('key'))

        # Is it a header?
        match = REGROU.match(line)
        if match:
            groups.append(match.group('grouping'))

        # Is it a blank line?
        if REBLAN.match(line):
            groups = []

    return toopen, issues

class Gira(cli.Cli):
    '''Gira CLI class'''

    def __init__(self, server, project):
        '''Initialise parser and get cookie'''

        cli.Cli.__init__(self, history=True)

        self.server = server
        self.project = project
        self.prompt = (project if project else 'gira') + '% '
        self.wrapper = textwrap.TextWrapper(width=80)

        # Configuration
        self.cfg = ConfigParser.SafeConfigParser()
        self.cfg.read(self.directory + '/gira.cfg')

        # Arguments
        self.issuesparser.add_argument('-c', '--component')
        self.issuesparser.add_argument('-g', '--group',
                                       choices=['versions', 'components'])
        help = "show all issue states, included those closed"
        self.issuesparser.add_argument('-a', '--all', help=help,
                                       action='store_true')
        self.issuesparser.add_argument('-f', '--fixversion', nargs='+')
        self.issuesparser.add_argument('-m', '--maxresults', type=int,
                                       default=MAXRESULTS)
        self.issuesparser.add_argument('--dryrun', '-n', action='store_true')
        self.issuesparser.add_argument('--verbose', '-v', action='store_true')

        self.searchparser.add_argument('jql', nargs='+')
        self.searchparser.add_argument('-m', '--maxresults', type=int,
                                       default=MAXRESULTS)

        self.useparser.add_argument('project')

        self.issueparser.add_argument('key', nargs='+')
        self.issueparser.add_argument('--dryrun', '-n', action='store_true')
        self.issueparser.add_argument('--verbose', '-v', action='store_true')

        self.createparser.add_argument('--dryrun', '-n', action='store_true')
        self.createparser.add_argument('--verbose', '-v', action='store_true')

        self.debugparser.add_argument('resource')

        # Sink for curl
        self.null = open(os.devnull, 'w')

        # Cookie
        self.cookiepath = self.directory + '/cookie'
        self.cookielock = threading.Lock()

        # Start up
        self.startupthread = threading.Thread(target=self.startupworker)
        self.startupthread.start()

    def startupworker(self):
        '''
        Start up in the background
        '''

        # Get a new cookie if needs be
        self.getcookie()

        # Load component and version completion
        if self.project:
            compl = open(self.directory + '/components', 'w')
            self.components(compl)
            compl.close()
            compl = open(self.directory + '/versions', 'w')
            self.versions(compl)
            compl.close()

    def getcookie(self, force=False):
        '''Get cookie'''

        self.cookielock.acquire()
        renew = False
        try:
            if time.time() - os.stat(self.cookiepath).st_mtime > 60 * 60 * 24:
                renew = True
        except OSError:
            renew = True

        if renew or force:
            returncode = 1
            while returncode != 0:
                print "Getting a fresh cookie... "
                args = ['get-cookie', '-u',
                        self.server + '/login', '-o',
                        self.cookiepath]
                returncode = subprocess.call(args)
        self.cookielock.release()

    def curl(self, res, method=None, data=None):
        '''Prepare, run curl and manage its output'''

        # Ask for a cookie if needs be
        self.getcookie()

        def runcurl():
            '''Run curl'''

            # Assemble arguments
            args = ['curl', '-b', self.cookiepath]
            if method and data:
                # str(data) not good enough because JIRA is picky on which
                # quotes to use, and json does it right
                args += ['-X', method, '-d', json.dumps(data), '-H',
                         'Content-Type: application/json']
                print "will change data"
            args += [url]

            # Run curl
            proc = subprocess.Popen(args, stdout=subprocess.PIPE,
                                    stderr=self.null)
            out, _ = proc.communicate()

            # Not sure we still get 'Unauthorized' HTML pages, probably just
            # JSON data with a 'errorMessages' key which we catch later on.
            for _ in range(int(self.cfg.get('jira', 'retry'))):
                try:
                    if out:
                        return json.loads(out)
                    else:
                        # PUT returns an empty string - nothing to return, then
                        return
                except ValueError:
                    # Ouput is HTML - something went wrong, stay in the loop
                    pass
            else:
                # Still getting HTML after so many retries
                print >> sys.stderr, UNAVAILMSG
                time.sleep(float(self.cfg.get('jira', 'retrywait')))
                return {}

        # Prepare
        url = self.server + URL + res

        # Run curl and ask for a cookie if needs be
        jsonout = runcurl()
        try:
            if jsonout['errorMessages'][1] == 'Login Required':
                self.getcookie(True)
                jsonout = runcurl()
        except (TypeError, KeyError, IndexError):
            pass

        # Report errors
        if jsonout and 'errors' in jsonout:
            for error in jsonout['errors']:
                msg = '%s: %s' % (error, jsonout['errors'][error])
                print >> sys.stderr, self.wrapper.fill(msg)

        return jsonout

    def versions(self, *fhls):
        '''
        Populate versions
        '''

        if not self.project:
            print >> sys.stderr, "Project not set"
            return

        try:
            # Query
            res = '/project/' + self.project
            versions = [ver['name'] for ver in self.curl(res)['versions']]

            # Report
            for fhl in fhls:
                for version in sorted(versions):
                    print >> fhl, version
        except KeyError:
            pass

    def run_versions(self, _):
        '''Run versions command'''

        compl = open(self.directory + '/components', 'w')
        tempfhl = open(self.temp, 'w')
        self.versions(sys.stdout, tempfhl, compl)
        tempfhl.close()
        compl.close()

    def issues(self, query, group, maxresults):
        '''Query issues and organise their fields'''

        try:
            # Collect issues and their relationships
            result = self.search(query, maxresults)
        except KeyError:
            # No matching issue
            for msg in result['errorMessages']:
                print >> sys.stderr, self.wrapper.fill(msg)
            return

        if group == 'versions':
            versions = {}
        elif group == 'components':
            components = {}
        issues = {} # Need this structure anyway to subset later on

        for issue in result['issues']:
            # Key
            iss = {}

            # Fields
            fields = issue['fields']

            iss['asn'] = fields['assignee']['name'] \
                if fields['assignee'] else ''

            iss['components'] = [com['name'] for com in fields['components']]

            iss['versions'] = [ver['name'] for ver in fields['fixVersions']]

            iss['rep'] = fields['reporter']['name'] \
                if fields['reporter'] else ''

            iss['status'] = fields['status']['name']

            iss['summary'] = fields['summary'].strip()

            iss['subtasks'] = [subtask['key'] for subtask in fields['subtasks']]

            iss['parent'] = fields['parent'] if 'parent' in fields else None

            if group == 'versions':
                versstr = repr(iss['versions'])
                if versstr in versions:
                    versions[versstr]['issues'][issue['key']] = iss
                else:
                    versions[versstr] = {'versions': iss['versions'],
                                         'issues': {issue['key']: iss}}
            elif group == 'components':
                compstr = repr(iss['components'])
                if compstr in components:
                    components[compstr]['issues'][issue['key']] = iss
                else:
                    components[compstr] = {'components': iss['components'],
                                           'issues': {issue['key']: iss}}
            issues[issue['key']] = iss

        # Report
        tempfhl = open(self.temp, 'w')

        def mkgroup(heading, fields, grouping, group):
            '''Print tables for group'''

            print >> tempfhl, """\
# Prefix an issue line with 'o' to open it. Move lines between groups to
# change them. Editing lines has otherwise no effect."""
            print >> tempfhl

            for key in group:
                # Create new table
                rows = [heading]

                # Write header
                for grp in group[key][grouping]:
                    print >> tempfhl, '" ' + grp

                # Write table
                table(rows, group[key]['issues'], fields)
                print >> tempfhl

        def table(rows, issues, fields):
            '''Print table'''

            # Arrange issues for table
            for key in issues:
                issue = issues[key]
                subtasks = issue['subtasks']
                if not issue['parent'] or issue['parent']['key'] not in issues:
                    # Add row
                    rows.append(row(issues, key, fields))

                    if subtasks:
                        # Add subtasks
                        for subtask in subtasks[:-1]:
                            if subtask in issues:
                                rows.append(row(issues, subtask, fields, '├─>'))
                        if subtasks[-1] in issues:
                            rows.append(row(issues, subtasks[-1],
                                            fields, '└─>'))

            # Print table
            tab.tab(rows, spacing=2, fhl=tempfhl)

        if group == 'versions':
            mkgroup(["KEY", "ASSIGNEE", "REPORTER", "COMPONENTS",
                     "STATUS", "SUMMARY"],
                    ['asn', 'rep', 'components', 'status', 'summary'],
                    group, versions)
        elif group == 'components':
            mkgroup(["KEY", "ASSIGNEE", "REPORTER", "VERSIONS",
                     "STATUS", "SUMMARY"],
                    ['asn', 'rep', 'versions', 'status', 'summary'],
                    group, components)
        else:
            table([["KEY", "ASSIGNEE", "REPORTER", "COMPONENTS", "VERSIONS",
                    "STATUS", "SUMMARY"]],
                   issues,
                   ['asn', 'rep', 'components', 'versions', 'status',
                    'summary'])

        tempfhl.close()

        return issues

    def run_issues(self, args):
        '''Run issues command'''

        if not self.project:
            print >> sys.stderr, "Project not set"
            return

        # Get issues from version
        query = 'project = ' + self.project
        query += ' AND component = "%s"' % \
            args.component if args.component else ''
        query += ' AND fixVersion = "%s"' % \
            ' '.join(args.fixversion) if args.fixversion else ''
        if not args.all:
            query += ' AND status NOT IN (%s)' % \
                self.cfg.get('issues', 'closed')

        issues = self.issues(query, args.group, args.maxresults)

        # Open page file in Vim
        subprocess.call(['vim', '-S', self.directory + '/issues.vimrc',
                         self.temp])
        self.wintitle()

        # Parse data from issues file
        tempvim = open(self.temp)
        toopen, issuesedit = parseissues(tempvim, args.group)
        tempvim.close()

        # Only update grouped issues (for now)
        if args.group:
            for key in issuesedit:
                if not subset(issuesedit[key], issues[key]):
                    groups = [{'name': group} for group in
                              issuesedit[key][args.group]]
                    fields = {'fields': {args.group
                                         if args.group != 'versions'
                                         else 'fixVersions': groups}}
                    if not args.dryrun:
                        self.curl('/issue/' + key, 'PUT', fields)
                    if args.verbose:
                        pprint.pprint((key, fields))

        if toopen:
            def hook():
                readline.insert_text('issue ' + ' '.join(toopen))
                readline.redisplay()
            readline.set_pre_input_hook(hook)

    def search(self, jql, maxresults=50):
        '''Run search query'''

        return self.curl('/search?jql=%s&maxResults=%d' % \
                         (urllib.quote(jql), maxresults))

    def components(self, *fhls):
        '''
        Populate components
        '''

        if not self.project:
            print >> sys.stderr, "Project not set"
            return

        try:
            # Query
            res = '/project/' + self.project
            components = [comp['name'] for comp in self.curl(res)['components']]

            # Report
            for fhl in fhls:
                for component in sorted(components):
                    print >> fhl, component
        except KeyError:
            pass

    def run_components(self, _):
        '''Run components command'''

        compl = open(self.directory + '/components', 'w')
        tempfhl = open(self.temp, 'w')
        self.components(sys.stdout, tempfhl, compl)
        tempfhl.close()
        compl.close()

    def run_search(self, args):
        '''Run search command'''

        jql = ['"%s"' % word if ' ' in word else word for word in args.jql]
        self.issues(' '.join(jql), None, args.maxresults)

        # Open page file in Vim
        subprocess.call(['vim', '-S', self.directory + '/issues.vimrc',
                         self.temp])
        self.wintitle()

        # Parse data from issues file
        tempvim = open(self.temp)
        toopen, _ = parseissues(tempvim)
        tempvim.close()

        # Open issues if needs be
        if toopen:
            def hook():
                readline.insert_text('issue ' + ' '.join(toopen))
                readline.redisplay()
            readline.set_pre_input_hook(hook)

    def run_projects(self, _):
        '''Run projects command'''

        projects = [[prj['name'], prj['key']] for prj in self.curl('/project')]
        projects.insert(0, ["PROJECT", "KEY"])
        tempfhl = open(self.temp, 'w')
        for fhl in sys.stdout, tempfhl:
            tab.tab(projects, fhl=fhl)
        tempfhl.close()

    def run_use(self, args):
        '''Run use command'''

        for project in self.curl('/project'):
            if args.project in (project['name'], project['key']):
                self.project = project['key']
                self.prompt = self.project + '% '

                # Load component and version completion
                compl = open(self.directory + '/components', 'w')
                self.components(compl)
                compl.close()
                compl = open(self.directory + '/versions', 'w')
                self.versions(compl)
                compl.close()

                break

    def run_issue(self, args):
        '''Run issue command'''

        with open(self.temp, 'w') as fhl:
            issues = {}
            for key in args.key:
                issues[key] = self.curl('/issue/%s?expand=transitions' % key)
                try:
                    self.form(fhl, issues[key], False)
                except KeyError:
                    return

        # Open page file in Vim
        subprocess.call(['vim', '-S', self.directory + '/issue.vimrc',
                         self.temp])
        self.wintitle()

        # Parse data from issue file
        tempvim = open(self.temp)
        issuesedit = parseissue(tempvim)
        tempvim.close()

        for key, fields in issuesedit:
            # Update fields
            if not subset(fields['fields'], issues[key]['fields']):
                if not args.dryrun:
                    self.curl('/issue/' + key,
                              'PUT', {'fields': fields['fields']})
                if args.verbose:
                    pprint.pprint({'fields': fields['fields']})

            # Add comment
            comment = fields['comment']
            if comment:
                if not args.dryrun:
                    self.curl('/issue/%s/comment' % key,
                              'POST', {'body': comment})

            # Edit comments
            comments = issues[key]['fields']['comment']['comments']
            for i, comment in enumerate(fields['comments']):
                if not subset(comment, comments[i]):
                    cid = comments[i]['id']
                    if not args.dryrun:
                        self.curl('/issue/%s/comment/%s' % (key, cid),
                                  'PUT', comment)

            # Perform transition
            for transition in issues[key]['transitions']:
                # No real need to check if any change is needed since
                # states and transitions have different names even if
                # they relate to each other and this will cause this
                # test to fail:
                if fields['transition'] == transition['name']:
                    if not args.dryrun:
                        self.curl('/issue/%s/transitions' % key, 'POST',
                                  {'transition': transition['id']})
                    break

    def form(self, fhl, issue, new):
        '''Print issue form'''

        fields = issue['fields']

        print >> fhl, """\
# The green title and fields in yellow are editable, the other ones aren't. The
# 'Status' field expects specific values which are suggested in the in-line
# comment.  You can insert several lines of Component/Version fields.
# Available ones can be completed from with CTRL-X CTRL-U."""
        print >> fhl

        # Header
        print >> fhl, ">>> %s/%s %s" % (fields['project']['key'],
                                        issue['key'],
                                        fields['summary'])

        # Type and status
        if new:
            fmt = "Type:       {0:%d} Status:     {1}" % WIDTH
            print >> fhl, fmt.format(fields['issuetype']['name'],
                                     fields['status']['name'])
        else:
            fmt = "Type:       {0:%d} Status:     {1} # {2}" % WIDTH
            print >> fhl, fmt.format(fields['issuetype']['name'],
                                     fields['status']['name'],
                                     ', '.join([trans['name']
                                                for trans
                                                in issue['transitions']]))

        # Priority and resolution
        priority = fields['priority']
        resolution = fields['resolution']
        fmt = "Priority:   {0:%d} Resolution: {1}" % WIDTH
        print >> fhl, fmt.format(priority['name'] if priority else '',
                                 resolution['name'] if resolution else '')

        # Components and versions
        for component, version in itertools.izip_longest(fields['components'],
                                                         fields['fixVersions']):
            if component and version:
                fmt = "Component:  {0:%d} Version:    {1}" % WIDTH
                values = (component['name'], version['name'])
            elif component:
                fmt = "Component:  {0:%d}" % WIDTH
                values = (component['name'],)
            elif version:
                values = ('', version['name'],)
                fmt = "            {0:%d} Version:    {1}" % WIDTH
            print >> fhl, fmt.format(*values)

        # Creation date and security
        if 'security' in fields:
            fmt =  "Created:    {0:%d} Security:   {1}" % WIDTH
            print >> fhl, fmt.format(fields['created'][:10],
                                     fields['security']['name'])
        else:
            fmt =  "Created:    {0:%d}" % WIDTH
            print >> fhl, fmt.format(fields['created'][:10])

        # Update date and assignee
        asn = fields['assignee']
        asn = asn['name'] if asn else ''
        fmt =  "Updated:    {0:%d} Assignee:   {1}" % WIDTH
        print >> fhl, fmt.format(fields['updated'][:10], asn)

        # Resolution date and reporter
        resdate = fields['resolutiondate']
        fmt =  "Resolved:   {0:%d} Reporter:   {1}" % WIDTH
        print >> fhl, \
            fmt.format(resdate[:10] if resdate else '',
                       fields['reporter']['name'])

        # Description
        print >> fhl
        print >> fhl, "Description:"
        if fields['description']:
            print >> fhl, fields['description'].replace('\r', '')

        # Comments
        if fields['comment']['comments']:
            for comment in fields['comment']['comments']:
                print >> fhl
                print >> fhl, "Comment from %s, %s:" % \
                    (comment['author']['name'], comment['updated'][:10])
                print >> fhl, comment['body'].replace('\r', '')

        if not new:
            print >> fhl
            print >> fhl, "New Comment?"
            print >> fhl

        # Footer
        print >> fhl, "<<< %s/%s %s" % (fields['project']['key'],
                                        issue['key'],
                                        fields['summary'])
        print >> fhl

    def run_create(self, args):
        '''Run create command'''

        # Write form
        fhl = open(self.temp, 'w')
        issue = {'fields':
                    {'assignee': None,
                     'comment': {'comments': []},
                     'components': [{'name': 'TODO'}], # pylint: disable=fixme
                     'created': 'Now',
                     'description': 'TODO', # pylint: disable=fixme
                     'fixVersions': [{'name': 'TODO'}], # pylint: disable=fixme
                     'issuetype': {'name': 'TODO'}, # pylint: disable=fixme
                     'priority': {'name': 'TODO'}, # pylint: disable=fixme
                     'project': {'key': self.project},
                     'reporter': {'name': os.environ['USER']},
                     'resolution': {'name': ''},
                     'resolutiondate': '',
                     'security': {'name': 'Internal Data'},
                     'status': {'name': 'Open'},
                     'summary': 'TODO', # pylint: disable=fixme
                     'updated': 'Now'},
                 'key': self.project + '-???',
                 'transitions': []}
        self.form(fhl, issue, True)
        fhl.close()

        # Open page file in Vim
        subprocess.call(['vim', '-S', self.directory + '/issue.vimrc',
                         self.temp])
        self.wintitle()

        # Parse date from page file
        tempvim = open(self.temp)
        issuesedit = parseissue(tempvim)
        tempvim.close()

        # Write issue data to JIRA
        for _, fields in issuesedit:
            if not subset(fields['fields'], issue['fields']):
                if not args.dryrun:
                    newissue = self.curl('/issue', 'POST',
                                         {'fields': fields['fields']})
                if args.verbose:
                    pprint.pprint({'fields': fields['fields']})
                if 'key' in newissue:
                    print "Created %s" % newissue['key']

    def run_debug(self, args):
        '''Run query and print raw result'''

        jsonoutput = self.curl(args.resource)
        tempfhl = open(self.temp, 'w')
        tempfhl.write(pprint.pformat(jsonoutput))
        tempfhl.close()
        pprint.pprint(jsonoutput)

def main():
    '''Main function'''

    # Arguments
    parser = ArgumentParser(formatter_class=ArgumentDefaultsHelpFormatter)
    parser.add_argument('-s', '--server', default='https://example.net/jira')
    parser.add_argument('project', nargs='?')
    args = parser.parse_args()

    # CLI
    Gira(args.server, args.project).loop()

if __name__ == '__main__':
    main()
